### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by jone-VB** [davidkreidler/SCD4x_CO2_Sensor_ESP32#24]
Hello,

i want to change the IP port. So i have to compile the project. But the compiler always exit with a error. (Last stable Arduino IDE)

/appdata/local/arduino15/packages/esp32/tools/esp-xs2/2302/bin/../lib/gcc/xtensa-esp32s2-elf/12.2.0/../../../../xtensa-esp32s2-elf/bin/ld.exe: AppData\Local\Temp\arduino\sketches\C0C28A831D33C2C6251395E964439267/OpenCO2_Sensor.ino.elf section `.rtc.data' will not fit in region `rtc_slow_seg'
appdata/local/arduino15/packages/esp32/tools/esp-xs2/2302/bin/../lib/gcc/xtensa-esp32s2-elf/12.2.0/../../../../xtensa-esp32s2-elf/bin/ld.exe: RTC_SLOW segment data does not fit.
/appdata/local/arduino15/packages/esp32/tools/esp-xs2/2302/bin/../lib/gcc/xtensa-esp32s2-elf/12.2.0/../../../../xtensa-esp32s2-elf/bin/ld.exe: region `rtc_slow_seg' overflowed by 120 bytes
collect2.exe: error: ld returned 1 exit status

exit status 1

Compilation error: exit status 1

Do you have a idea?
Thanks

**Comment by davidkreidler** [comment]
Hey @jone-VB
please use in Boards Manager the esp32  Version 2.0.13

Thanks!
David

**Comment by jone-VB** [comment]
Thanks. Works

**Comment by lux-6000** [comment]
I have the same problem here. I have switched to Version 2.0.13 in the Boards Manager but no improvement.
Compiling the original code does not work with my settings.
![grafik](https://github.com/user-attachments/assets/c94e91ac-c4e9-4641-a17c-5bf66996d5e0)

I am trying to change the code so the esp32 can store more than just 24h history by reducing the sampling rate. no changing of the size of the arrays. because i think they are already pretty maxed out.

**Comment by davidkreidler** [comment]
Hey @lux-6000 thanks for reaching out. It looks like you installed esp32 version 3.07. In your picture its the one below. To compile master you would need to downgrade this one.

Im also working on a PR to enable an esp32 version update here https://github.com/davidkreidler/OpenCO2_Sensor/pull/25/files 
You can see that other variables also need to be changed for example for the time to be displayed correctly. 

Regarding your last point writing more values and being persistent would be possible in the eeprom but it might wear out over time.

**Comment by davidkreidler** [comment]
To increase the time between stored measurements (from 30 seconds) it would need to be changed here https://github.com/davidkreidler/OpenCO2_Sensor/blob/main/OpenCO2_Sensor.ino#L630 and at some other areas to be displayed correctly. 

Maybe its best to store longer term measurements externally for example via [internet-pi](https://github.com/geerlingguy/internet-pi). First connect the OpenCO2 Sensor to your Wi-Fi network and follow the instructions https://www.youtube.com/watch?v=Cmr5VNALRAg Then download the https://raw.githubusercontent.com/davidkreidler/OpenCO2_Sensor/main/grafana_OpenCO2_Sensor.json and import it into Grafana.
