### ISSUE TITLE
getDataReadyFlag not found

### ISSUE THREAD

**Issue by chrho** [davidkreidler/SCD4x_CO2_Sensor_ESP32#3]
Hallo,

 wenn ich den main branch nehme und wie in der Readme beschrieben die Libs über die Arduino IDE installiere bekomme ich beim bauen die Fehlermeldung das es die Funktion nicht gibt. Ich hab auch in den Code der Lib geschaut da ist sie nicht enthalten. Kannst du mir sagen was ich falsch mache?

Gruß Christoph

**Comment by davidkreidler** [comment]
Hey @chrho,
das ist eine sehr hilfreiche frage! Du benötigst die neuste Version der arduino scd4x Library:
github.com/Sensirion/arduino-i2c-scd4x in folgendem commit wurde die Funktion umbenannt:
https://github.com/Sensirion/arduino-i2c-scd4x/commit/4ec07965f30f32f4320960a04aadb7a19e6499c7

Einfach als ZIP downloaden und in der Arduino IDE importieren oder in den libraries Ordner entpacken.

Gruß
David
